title_to_country = {
    "Tunez": "Tunisia",
    "Suiza": "Switzerland",
    "Singapur": "Singapore",
    "Egipto": "Egypt",
    "Ruanda": "Rwanda",
    "Brasil": "Brazil",
    "Camboya": "Cambodia",
    "Inglaterra_y_Gales": "England and Wales",
    "South_Korea-es": "South Korea",
    "Canadian_Charter_of_Rights_and_Freedoms": "Canada",
    "Azerbaiyan": "Azerbaijan",
    "Alemania": "Germany",
    "Camerun": "Cameroon",
    "Suazilandia": "Swaziland",
    "Filipinas": "Philippines",
    "Francia": "France",
    "Japon": "Japan",
    "Zimbabue": "Zimbabwe",
    "Tailandia": "Thailand",
    "Urugay": "Uruguay",
    "Sudafrica": "South Africa",
    "Libia": "Libya",
    "Maurice-fr": "Mauritius",
    "South_Korea": "South Korea",
    "United_State_Supreme_Court": "United States",
    "Cote_dIvoire": "Ivory Coast",
    "cote divoire": "Ivory Coast",
    "Lao's_People_Democratic_Republic": "Laos",
    "Chinese-English_Legal_Lexicon": "China",
    "Chinese_Law_Primer": "China",
    "Cairo_Declaration_on_Human_Rights_in_Islam": "Egypt",
    "American_Bar_Association_Model_Rules_of_Professional_Conduct_-_Rule_3.1._Meritorious_Claims_and_Contentions": "United States",
    "Republique_du_Congo_(Congo-Brazzaville)": "Congo, Republic of the",
    "Democratic_Republic_of_Congo-fr": "Congo, Democratic Republic of the",
    "Democratic_Republic_of_Congo-es": "Congo, Democratic Republic of the",
    "Congo-brazzaville": "Congo, Republic of the",
    "Congo": "Congo, Democratic Republic of the",
    "Inglaterra": "England and Wales",
    "Japon": "Japan",
    "Malasia": "Malaysia",
    "Kenia": "Kenya",
    "Francais": "France",
    "Arabia saudi": "Saudi Arabia",
    "Republique Centrafricaine": "Central African Republic",
    "Suecia": "Sweden",
    "Corea del sur": "South Korea"
}


substring_to_country = {
    "American_": "United States",
    "American ": "United States",
    "american": "United States",
    "Chinese": "China",
    "chinese": "China",
    "Canadian": "Canada",
    "Cairo": "Egypt",
    "Zimbabwe": "Zimbabwe",
    "Ouagadougou": "Burkina Faso",
}